resources = {
    "en-US": {
        "cmdDefIdNotSpecified": "commandDefinition id is not specified",
        "cmdControlIdNotSpecified": "commandControl id is not specified",
        "deleteObjInvalid": "tobeDeleteObj is not a valid object",
        "cmdName": "Demo",
        "cmdDescription": "Demo Command",
        "inputChangedEventTriggered": "Input: {0} changed event triggered",
        "FailedInInputChangedEvent": "Input changed event failed: ",
        "cmdExecutedSuccessfully": "command: {0} executed successfully",
        "cmdExecutedFailed": "command executed failed: ",
        "cmdQATCreated": "QAT command created successfully",
        "cmdQATCreatedFailed": "QAT command created failed: ",
        "value": "Value",
        "checked": "Bool",
        "stringValue": "String Value",
        "defaultValue": "Default value",
        "selection": "Selection",
        "selectOne": "Select one",
        "dropDown": "Drop Down",
        "listItem1": "ListItem 1",
        "listItem2": "ListItem 2",
        "listItem3": "ListItem 3",
        "dropDown2": "Drop Down2",
        "slider": "Slider",
        "buttonRow": "Button Row",
        "distance": "Distance",
        "direction": "Direction",
        "direction2": "Direction2",
        "cmdPanelCreated": "Panel command created successfully",
        "cmdPanelCreatedFailed": "Panel command created failed: ",
        "demoButtonAddedToQAT": "A demo command button is successfully added to the Quick Access Toolbar",
        "demoButtonAddedToPanel": "A demo command is successfully added to the create panel in modeling workspace",
        "addInStartFailed": "AddIn Start Failed : ",
        "addInStopFailed": "AddIn Stop Failed : "
    },
    "zh-CN": {
        "cmdDefIdNotSpecified": "没有指定commandDefinition id",
        "cmdControlIdNotSpecified": "没有指定commandControl id",
        "deleteObjInvalid": "tobeDeleteObj不是一个有效的对象",
        "cmdName": "演示",
        "cmdDescription": "演示命令",
        "inputChangedEventTriggered": "触发事件Input: {0} changed",
        "FailedInInputChangedEvent": "输入变化事件失败: ",
        "cmdExecutedSuccessfully": "命令: {0} 执行成功",
        "cmdExecutedFailed": "命令执行失败 ",
        "cmdQATCreated": "QAT命令创建成功",
        "cmdQATCreatedFailed": "QAT创建失败: ",
        "value": "值",
        "checked": "布尔",
        "stringValue": "字符串",
        "defaultValue": "默认值",
        "selection": "选择",
        "selectOne": "选一个",
        "dropDown": "下拉框",
        "listItem1": "列表项 1",
        "listItem2": "列表项 2",
        "listItem3": "列表项 3",
        "dropDown2": "下拉框2",
        "slider": "滚动条",
        "buttonRow": "按钮行",
        "distance": "距离",
        "direction": "方向",
        "direction2": "方向2",
        "cmdPanelCreated": "面板命令创建成功",
        "cmdPanelCreatedFailed": "面板命令创建失败: ",
        "demoButtonAddedToQAT": "一个演示命令被成功的添加到QAT",
        "demoButtonAddedToPanel": "一个演示命令被成功的添加到创建面板",
        "addInStartFailed": "附加模块启动失败 : ",
        "addInStopFailed": "附加模块启动成功 : "
    }
};